
//app actions
export const REHYDRATE_COMPLETE = 'REHYDRATE_COMPLETE';
export const RESET_APP = 'RESET_APP';
export const CLOSE_SLIDESHOW = 'CLOSE_SLIDESHOW';
export const UPDATE_INTERNET_STATE_SUCCESS = 'UPDATE_INTERNET_STATE_SUCCESS';
export const DEFAULT = 'DEFAULT';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const OPEN_CALL_SCREEEN = 'OPEN_CALL_SCREEEN';


//encrypt app actions
export const SET_ENCRYPT_PRIVATE_KEY = 'SET_ENCRYPT_PRIVATE_KEY';
export const SET_ENCRYPT_PUBLIC_KEY = 'SET_ENCRYPT_PUBLIC_KEY';
export const SET_ENCRYPT_MESSAGE_TOKEN = 'SET_ENCRYPT_MESSAGE_TOKEN';


//user actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const REFRESH_USER_SUCCESS = 'REFRESH_USER_SUCCESS';
export const REFRESH_USER_REQUEST = 'REFRESH_USER_REQUEST';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_NOT_ACTIVATED = 'SIGNUP_NOT_ACTIVATED';
export const LOGIN_2FA_REQUIRED = 'LOGIN_2FA_REQUIRED';
export const LOGIN_2FA_REQUEST = 'LOGIN_2FA_REQUEST';
export const LOGIN_2FA_SUCCESS = 'LOGIN_2FA_SUCCESS';
export const LOGIN_2FA_ERROR = 'LOGIN_2FA_ERROR';
export const LOGIN_2FA_CONFIRM_REQUEST = 'LOGIN_2FA_CONFIRM_REQUEST';
export const LOGIN_2FA_CONFIRM_SUCCESS = 'LOGIN_2FA_CONFIRM_SUCCESS';
export const LOGIN_2FA_CONFIRM_ERROR = 'LOGIN_2FA_CONFIRM_ERROR';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_RE_USER_SUCCESS = 'UPDATE_RE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';


//contacts actions
export const GET_USER_CONTACTS_SHOW_LOADER = 'GET_USER_CONTACTS_SHOW_LOADER';
export const GET_USER_CONTACTS_REQUEST = 'GET_USER_CONTACTS_REQUEST';
export const GET_USER_CONTACTS_SUCCESS = 'GET_USER_CONTACTS_SUCCESS';
export const GET_USER_CONTACTS_ERROR = 'GET_USER_CONTACTS_ERROR';
export const SELECT_CONTACT = 'SELECT_CONTACT';
export const UPDATE_CONTACT_CS_REQUEST = 'UPDATE_CONTACT_CS_REQUEST';
export const UPDATE_CONTACT_CS = 'UPDATE_CONTACT_CS';
export const UPDATE_CONTACT_CS_ERROR = 'UPDATE_CONTACT_CS_ERROR';
export const REFRESH_MY_CONTACTS = 'REFRESH_MY_CONTACTS';
export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';
export const ADD_NEW_CONTACT = 'ADD_NEW_CONTACT';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';
export const SEARCH_CONTACT_REQUEST = 'SEARCH_CONTACT_REQUEST';
export const SEARCH_CONTACT_SUCCESS = 'SEARCH_CONTACT_SUCCESS';
export const SEARCH_CONTACT_ERROR = 'SEARCH_CONTACT_ERROR';


//call-log actions
export const GET_CALL_LOG_SHOW_LOADER = 'GET_CALL_LOG_SHOW_LOADER';
export const GET_CALL_LOG_REQUEST = 'GET_CALL_LOG_REQUEST';
export const GET_CALL_LOG_SUCCESS = 'GET_CALL_LOG_SUCCESS';
export const GET_CALL_LOG_ERROR = 'GET_CALL_LOG_ERROR';
export const SELECT_CALL_LOG_CONTACT = 'SELECT_CALL_LOG_CONTACT';
export const REFRESH_CALL_HISTORY = 'REFRESH_CALL_HISTORY';


//call actions
export const CREATE_CALL_REQUEST = 'CREATE_CALL_REQUEST';
export const CREATE_CALL_SUCCESS = 'CREATE_CALL_SUCCESS';
export const CREATE_CALL_ERROR = 'CREATE_CALL_ERROR';


//socket actions events
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';


//call actions
export const ON_CALL = 'ON_CALL';
export const EMIT_CALL = 'EMIT_CALL';
export const ON_CALL_ACCEPTED = 'ON_CALL_ACCEPTED';
export const EMIT_CALL_ACCEPTED = 'EMIT_CALL_ACCEPTED';
export const ON_CANCEL_CALL = 'ON_CANCEL_CALL';
export const EMIT_CANCEL_CALL = 'EMIT_CANCEL_CALL';
export const ON_COMPLETE_CALL = 'ON_COMPLETE_CALL';
export const EMIT_COMPLETE_CALL = 'EMIT_COMPLETE_CALL';
export const ON_CALL_NO_ANSWER = 'ON_CALL_NO_ANSWER';
export const RESET_CALL = 'RESET_CALL';
export const SET_VIDEO_CALL = 'SET_VIDEO_CALL';
export const ON_REMOTE_VIDEO_IS_ENABLED = 'ON_REMOTE_VIDEO_IS_ENABLED';
export const ON_REMOTE_AUDIO_IS_ENABLED = 'ON_REMOTE_AUDIO_IS_ENABLED';
export const EMIT_SET_ENABLE_LOCAL_VIDEO = 'EMIT_SET_ENABLE_LOCAL_VIDEO';
export const EMIT_LOCAL_AUDIO_IS_ENABLED = 'EMIT_LOCAL_AUDIO_IS_ENABLED';
export const ON_SET_SPEAKER_PHONE_ON = 'ON_SET_SPEAKER_PHONE_ON';
export const SET_CALL_ID = 'SET_CALL_ID';
export const START_SYSTEM_CALL = 'START_SYSTEM_CALL';
export const END_SYSTEM_CALL = 'END_SYSTEM_CALL';
export const START_CALL_FROM_SYSTEM_CALL_HISTORY = 'START_CALL_FROM_SYSTEM_CALL_HISTORY';

export const EMIT_CALL_SUCCESS = 'EMIT_CALL_SUCCESS';
export const EMIT_CANCEL_CALL_SUCCESS = 'EMIT_CANCEL_CALL_SUCCESS';
export const EMIT_CALL_COMPLETE_SUCCESS = 'EMIT_CALL_COMPLETE_SUCCESS';
export const EMIT_CALL_TO = 'EMIT_CALL_TO';


//track actions
export const SET_LOCAL_TRACK = 'SET_LOCAL_TRACK';
export const RESET_LOCAL_TRACK = 'RESET_LOCAL_TRACK';
export const LOAD_TRACK_ERRO = 'LOAD_TRACK_ERRO';


//navigation actions
export const NAVIGATION_SET_CURRENT_SCREEN_INDEX = 'NAVIGATION_SET_CURRENT_SCREEN_INDEX';


// push token
export const PUSH_TOKEN_REQUEST = 'PUSH_TOKEN_REQUEST';
export const PUSH_TOKEN_SAVE_SUCCESS = 'PUSH_TOKEN_SAVE_SUCCESS';
export const PUSH_TOKEN_SAVE_ERROR = 'PUSH_TOKEN_SAVE_ERROR';


// talks actions
export const TALKS_SELECT_CONTACT = 'TALKS_SELECT_CONTACT';

export const TALKS_GET_CONVERSATIONS_REQUEST = 'TALKS_GET_CONVERSATIONS_REQUEST';
export const TALKS_GET_CONVERSATIONS_SUCCESS = 'TALKS_GET_CONVERSATIONS_SUCCESS';
export const TALKS_GET_CONVERSATIONS_ERROR = 'TALKS_GET_CONVERSATIONS_ERROR';
export const TALKS_GET_CONVERSATIONS_SHOW_LOADER = 'TALKS_GET_CONVERSATIONS_SHOW_LOADER';
export const TALKS_REFRESH_CONVERSATIONS = 'TALKS_REFRESH_CONVERSATIONS';
export const TALKS_UPDATE_LAST_MSG_CONVERSATIONS_REQUEST = 'TALKS_UPDATE_LAST_MSG_CONVERSATIONS_REQUEST';
export const TALKS_UPDATE_LAST_MSG_CONVERSATIONS_ERROR = 'TALKS_UPDATE_LAST_MSG_CONVERSATIONS_ERROR';
export const TALKS_UPDATE_LAST_MSG_STATUS_CONVERSATIONS_REQUEST = 'TALKS_UPDATE_LAST_MSG_STATUS_CONVERSATIONS_REQUEST';
export const TALKS_UPDATE_LAST_MSG_STATUS_CONVERSATIONS_ERROR = 'TALKS_UPDATE_LAST_MSG_STATUS_CONVERSATIONS_ERROR';
export const TALKS_CHOICE_CONTACT = 'TALKS_CHOICE_CONTACT';
export const TALKS_CREATE_CONVERSATIONS_GROUP_REQUEST = 'TALKS_CREATE_CONVERSATIONS_GROUP_REQUEST';
export const TALKS_CREATE_CONVERSATIONS_GROUP_SUCCESS = 'TALKS_CREATE_CONVERSATIONS_GROUP_SUCCESS';
export const TALKS_CREATE_CONVERSATIONS_GROUP_ERROR = 'TALKS_CREATE_CONVERSATIONS_GROUP_ERROR';
export const TALKS_CLEAR_CHOICE_CONTACT = 'TALKS_CLEAR_CHOICE_CONTACT';
export const TALKS_RENAME_CONVERSATIONS_GROUP_REQUEST = 'TALKS_RENAME_CONVERSATIONS_GROUP_REQUEST';
export const TALKS_RENAME_CONVERSATIONS_GROUP_SUCCESS = 'TALKS_RENAME_CONVERSATIONS_GROUP_SUCCESS';
export const TALKS_RENAME_CONVERSATIONS_GROUP_ERROR = 'TALKS_RENAME_CONVERSATIONS_GROUP_ERROR';
export const TALKS_LEAVE_CONVERSATIONS_GROUP_REQUEST = 'TALKS_LEAVE_CONVERSATIONS_GROUP_REQUEST';
export const TALKS_LEAVE_CONVERSATIONS_GROUP_SUCCESS = 'TALKS_LEAVE_CONVERSATIONS_GROUP_SUCCESS';
export const TALKS_LEAVE_CONVERSATIONS_GROUP_ERROR = 'TALKS_LEAVE_CONVERSATIONS_GROUP_ERROR';
export const TALKS_ON_ADD_CREATED_CONVERSATION = 'TALKS_ON_ADD_CREATED_CONVERSATION';
export const TALKS_ON_CHANGE_CONVERSATION_TITLE = 'TALKS_ON_CHANGE_CONVERSATION_TITLE';
export const TALKS_ON_ADD_NEW_PARTICIPANT_TO_CONVERSATION = 'TALKS_ON_ADD_NEW_PARTICIPANT_TO_CONVERSATION';
export const TALKS_ON_REMOVE_PARTICIPANT_FROM_CONVERSATION = 'TALKS_ON_REMOVE_PARTICIPANT_FROM_CONVERSATION';
export const TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_REQUEST = 'TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_REQUEST';
export const TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_SUCCESS = 'TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_SUCCESS';
export const TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_ERROR = 'TALKS_DELETE_PARTICIPANT_FROM_CONVERSATIONS_GROUP_ERROR';
export const TALKS_UPDATE_CONVERSTATION_TOTAL_UNREAD_COUNT = 'TALKS_UPDATE_CONVERSTATION_TOTAL_UNREAD_COUNT';
export const TALKS_SHOW_TYPING = 'TALKS_SHOW_TYPING';
export const TALKS_HIDE_TYPING = 'TALKS_HIDE_TYPING';
export const EMIT_TALKS_TYPING = 'EMIT_TALKS_TYPING';
export const EMIT_TALKS_TYPING_ERROR = 'EMIT_TALKS_TYPING_ERROR';


// chat actions
export const CHAT_SELECT_CONVERSATION = 'CHAT_SELECT_CONVERSATION';
export const CHAT_SEND_MESSAGE_REQUEST = 'CHAT_SEND_MESSAGE_REQUEST';
export const CHAT_SEND_MESSAGE_SUCCESS = 'CHAT_SEND_MESSAGE_SUCCESS';
export const CHAT_SEND_MESSAGE_ERROR = 'CHAT_SEND_MESSAGE_ERROR';
export const CHAT_ADD_MESSAGE_REQUEST = 'CHAT_ADD_MESSAGE_REQUEST';
export const CHAT_ADD_MESSAGE_SUCCESS = 'CHAT_ADD_MESSAGE_SUCCESS';
export const CHAT_ADD_MESSAGE_ERROR = 'CHAT_ADD_MESSAGE_ERROR';
export const CHAT_GET_RECIPIENT_CONVERSATION_REQUEST = 'CHAT_GET_RECIPIENT_CONVERSATION_REQUEST';
export const CHAT_GET_RECIPIENT_CONVERSATION_SUCCESS = 'CHAT_GET_RECIPIENT_CONVERSATION_SUCCESS';
export const CHAT_GET_RECIPIENT_CONVERSATION_ERROR = 'CHAT_GET_RECIPIENT_CONVERSATION_ERROR';
export const CHAT_CREATE_CONVERSATION_REQUEST = 'CHAT_CREATE_CONVERSATION_REQUEST';
export const CHAT_CREATE_CONVERSATION_SUCCESS = 'CHAT_CREATE_CONVERSATION_SUCCESS';
export const CHAT_CREATE_CONVERSATION_ERROR = 'CHAT_CREATE_CONVERSATION_ERROR';
export const CHAT_UPDATE_MESSAGE_TEMP_ID_REQUEST = 'CHAT_UPDATE_MESSAGE_TEMP_ID_REQUEST';
export const CHAT_UPDATE_MESSAGE_TEMP_ID_ERROR = 'CHAT_UPDATE_MESSAGE_TEMP_ID_ERROR';
export const CHAT_UPDATE_MESSAGE_STATUS_REQUEST = 'CHAT_UPDATE_MESSAGE_STATUS_REQUEST';
export const CHAT_UPDATE_MESSAGE_STATUS_ERROR = 'CHAT_UPDATE_MESSAGE_STATUS_ERROR';
export const CHAT_SET_MESSAGE_AS_READ_REQUEST = 'CHAT_SET_MESSAGE_AS_READ_REQUEST';
export const CHAT_SET_MESSAGE_AS_READ_SUCCESS = 'CHAT_SET_MESSAGE_AS_READ_SUCCESS';
export const CHAT_SET_MESSAGE_AS_READ_ERROR = 'CHAT_SET_MESSAGE_AS_READ_ERROR';
export const CHAT_UPDATE_MESSAGE_OG_TAGS_REQUEST = 'CHAT_UPDATE_MESSAGE_OG_TAGS_REQUEST';
export const CHAT_UPDATE_MESSAGE_OG_TAGS_ERROR = 'CHAT_UPDATE_MESSAGE_OG_TAGS_ERROR';
export const GET_STICKER_PACKS_REQUEST = 'GET_STICKER_PACKS_REQUEST';
export const GET_STICKER_PACKS_SUCCESS = 'GET_STICKER_PACKS_SUCCESS';
export const SELECT_STICKER_PACK_REQUEST = 'SELECT_STICKER_PACK_REQUEST';
export const SELECT_STICKER_PACK_SUCCESS = 'SELECT_STICKER_PACK_SUCCESS';
export const CHAT_UPDATE_MESSAGE_UPLOAD_PROGRESS_SUCCESS = 'CHAT_UPDATE_MESSAGE_UPLOAD_PROGRESS_SUCCESS';
export const CHAT_CANCEL_MESSAGE_FILE_UPLOAD = 'CHAT_CANCEL_MESSAGE_FILE_UPLOAD';
export const MESSAGE_FILE_UPLOADED_DONE = 'MESSAGE_FILE_UPLOADED_DONE';
export const MESSAGE_FILE_UPLOADED_PROGRESS = 'MESSAGE_FILE_UPLOADED_PROGRESS';
